### ISSUE TITLE
머신에 Kafka를 설치해야 할 경우

### ISSUE THREAD

**Issue by kwonslog** [kwonslog/how-to-use-kafka#8]
### 목적
> 인프라팀의 지원을 받을 수 있다면 좋겠지만 여건상 불가능한 상황이다. 그래서 운영 환경을 위한 기본적인 설정법까지만 정리하려 한다.

### 주키퍼 서버의 개수는?
> 권장 서버의 개수는 3이다. 
> 주키퍼 서버는 리더를 선출하기 위해 투표 방식을 사용하는데 과반수를 충족하려면 홀수로 설정해야 한다.
> 일단 3개로 구성하고 필요시 추가하는 방향으로 가면 된다.

### 브로커 서버의 개수는?
> 브로커 서버도 권장 개수는 3이다. 내구성과 가용성을 위한 조치이며 반드시 3개일 필요는 없다.
> 1개 또는 2개로 구성 할 수 있지만 장애가 발생 했을 경우를 대비한다면 권장 개수로 시작하는 것이 좋다.

### 파티션의 개수는?
> 정해진 개수는 없다. 개수가 많을수록 처리량은 높아질 것이다. 물론 컨슈머의 개수도 이에 대응하여 늘려주어야 한다.
> 뻔한 얘기긴 하지만 실제 사용량을 유추하여 테스트하면서 율하는 방법이 최선이다.

### 복제 팩터의 개수는?
> 권장 개수는 2이상이다. 복제 팩터의 수가 많을 수록 장애 발생시 데이터가 손실 될 위험성이 낮아진다.
> 하지만 그만큼 복제로 인한 디스크 용량이나 네트워크 비용이 증가하게 된다.

---

### 주키퍼 서버 하드웨어 권장 스펙
- cpu : 멀티코어(4core 이상), 높은 클럭, 큰 cpu 캐시
- ram : 최소 권장 4gb 이상
- disk : ssd 사용(최소 권장 10 ~ 100gb)
- 네트워크 : 최소권장 1Gbps 이상

### 브로커 서버 하드웨어 권장 스펙
- cpu : 멀티코어(4core 이상), 높은 클럭, 큰 cpu 캐시
- ram : 최소 권장 8gb 이상
- disk : ssd 사용(최소 권장 10 ~ 100gb)
- 네트워크 : 최소권장 1Gbps 이상

### 구성방안은?
- 안정적인 운영을 위해서 각 서버는 1개의 머신을 사용하면 좋다. 즉 주키퍼 3, 브로커 3 이라면 총 6개의 머신이 필요.

- 물론 어떤 서비스인지 처리하는 데이터가 어느 정도인지에 따라 그 구성은 당연히 달라진다. 정확한건 역시 예상 수치를 가지고 테스트 해보는 방법 밖에 없을 것이다.

- 일단 머신의 수를 3개로 가정하고, 각 머신당 주키퍼 및 브로커 서버를 설치 하는 방향으로 진행하자.

---

### tickTime 값은 어디에 사용 됩니까?
- 세션 타임아웃과 관계가 있다.

### dataDir 경로는?
- 데이터 스냅샷과 로그 파일을 저장하는 경로를 설정 한다.
- 상대 경로인 경우 주키퍼 설치 위치 기준
- 절대 경로도 가능.

### clientPort 는?
- 주키퍼 서버로 연결하기 위한 포트 설정

### initLimit 는?
- 리더 서버가 선출되고 팔로워 서버가 리더 서버와 처음으로 동기화하는 데 허용되는 시간
- tickTime의 배수로 설정
- 팔로워가 이 시간 내에 리더와 동기화하지 못하면, 해당 팔로워는 연결을 종료.

### syncLimit 는?
- 리더와 팔로워 사이에 패킷을 주고받는 데 허용되는 최대 시간을 설정
- tickTime의 배수로 설정
- 팔로워가 이 시간 내에 요청에 대한 응답을 리더로부터 받지 못하면, 팔로워는 연결을 종료하고 새로운 리더 선출을 시작

### zoo.cfg 설정 예제
```
tickTime=2000
dataDir=/var/zookeeper
clientPort=2181
initLimit=5
syncLimit=2
server.1=zoo1:2888:3888
server.2=zoo2:2888:3888
server.3=zoo3:2888:3888
```
### server.x 는?
- 각 ZooKeeper 서버의  ID. 
- `2888`은 서버간 통신을 위한 포트 번호
- `3888`은 leader 선출을 위한 포트 번호
- 모든 ZooKeeper 서버는 동일한 설정을 가져야하므로 하나의 설정 파일을 모든 서버에 복사해야 한다.
- 각 서버는 자신의 서버 ID를 `dataDir`에 지정된 위치에 `myid`라는 파일을 생성하고, 그 파일에 서버 ID를 작성한다.
- 예를 들어, 서버 ID가 1인 경우, `myid` 파일에 "1"이라고 작성.

### 주키퍼 서버 실행을 위한 docker-compose.yml 파일 작성
```yml
version: '3'

services:
  service-zk-1:
    image: confluentinc/cp-zookeeper
    restart: always
    hostname: host-zk-1
    container_name: continer-zk-1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=host-zk-1:2888:3888,server.2=host-zk-2:2888:3888,server.3=host-zk-3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
    volumes:
      - ./docker-volume/zk1:/var/lib/zookeeper
    networks:
      - test-kafka-net

  service-zk-2:
    image: confluentinc/cp-zookeeper
    restart: always
    hostname: host-zk-2
    container_name: continer-zk-2
    ports:
      - 2182:2182
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=host-zk-1:2888:3888,server.2=host-zk-2:2888:3888,server.3=host-zk-3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
    volumes:
      - ./docker-volume/zk2:/var/lib/zookeeper
    networks:
      - test-kafka-net

  service-zk-3:
    image: confluentinc/cp-zookeeper
    restart: always
    hostname: host-zk-3
    container_name: continer-zk-3
    ports:
      - 2183:2183
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=host-zk-1:2888:3888,server.2=host-zk-2:2888:3888,server.3=host-zk-3:2888:3888
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
    volumes:
      - ./docker-volume/zk3:/var/lib/zookeeper
    networks:
      - test-kafka-net

networks:
  test-kafka-net:
    external: true
```
- 만약 주키퍼 서버를 각각 개별 머신에서 실행해야 한다면 hostname 값과 ZOO_SERVERS 값을 실제 호스트 이름이나 ip 주소를 사용해야 한다.
- AWS EC2의 경우 서버가 재부팅 되면 priate ip 가 변경이 된다. 이를 해결하려면 EIP를 사용하거나 보조 사설 IP(Secondary Private IP)를 사용할 수 있다. EIP의 경우 요금이 발생 할 수 있고, 보조 사설 IP는 무료다.

### 브로커 서버 실행을 위한 docker-compose.yml 파일 작성
```yml
version: '3'

services:
  service-kf-1:
    image: confluentinc/cp-kafka
    restart: always
    hostname: host-kf-1
    ports:
      - "9092:9092"
    environment:
      #ID 값은 숫자만 가능
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host-kf-1:9092
      - KAFKA_ZOOKEEPER_CONNECT=host-zk-1:2181,host-zk-2:2181,host-zk-3:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DELETE_TOPIC_ENABLE=true
    networks:
      - test-kafka-net
  
  service-kf-2:
    image: confluentinc/cp-kafka
    restart: always
    hostname: host-kf-2
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host-kf-2:9093
      - KAFKA_ZOOKEEPER_CONNECT=host-zk-1:2181,host-zk-2:2181,host-zk-3:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DELETE_TOPIC_ENABLE=true
    networks:
      - test-kafka-net
  
  service-kf-3:
    image: confluentinc/cp-kafka
    restart: always
    hostname: host-kf-3
    ports:
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host-kf-3:9094
      - KAFKA_ZOOKEEPER_CONNECT=host-zk-1:2181,host-zk-2:2181,host-zk-3:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DELETE_TOPIC_ENABLE=true
    networks:
      - test-kafka-net

networks:
  test-kafka-net:
    external: true
```
- 먼저 주키퍼 서버를 실행하고, 브로커 서버를 실행하면 정상적으로 실행 되는 것을 확인 할 수 있다.

### 참고자료
- https://itdictionary-henry.tistory.com/20
- https://kubernetes.blog/m/34
- https://enterone.tistory.com/278
- https://118k.tistory.com/m/944
- https://saramin.github.io/2019-09-17-kafka/
